import matplotlib.pyplot as plt


# GRAPHICS TOOLS

def show_image(grid:list):
	r'Shows the changes generated by the A star algorithm'
	ptl.imshow(maze)
	return maze 


#GENERATE ROADS

def show_paths_maze(grid:list,points:list)->list:
	r'Shows the paths, the points to be covered'
	amaount_points=len(points)
	paths=[]
	for point in range(amaount_points):
		if point!=None:
			paths.append(astar(maze,points[point],points[point+1]))
	return paths




